/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

/**
 *
 * @author ryo
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class DeleteDialog extends javax.swing.JDialog {

    private boolean deleted = false;
    
    public DeleteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DeleteDialog(java.awt.Frame parent, boolean modal,String id, String judul, String genre, String harga) {
        super(parent, modal);
        initComponents();

        tfIdMember.setText(id);
        tfNama.setText(judul);
        tfTipePaket.setText(genre);
        tfCoach.setText(harga);

    }
    
    public boolean isDeleted() {
        return deleted; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfIdMember = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfTipePaket = new javax.swing.JTextField();
        tfCoach = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jId = new javax.swing.JLabel();
        jGenre = new javax.swing.JLabel();
        jJudul = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KONFIRMASI HAPUS DATA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 27, -1, -1));

        tfIdMember.setEditable(false);
        getContentPane().add(tfIdMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 128, 368, 39));

        tfNama.setEditable(false);
        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        getContentPane().add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 185, 368, 38));

        tfTipePaket.setEditable(false);
        getContentPane().add(tfTipePaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 241, 368, 36));

        tfCoach.setEditable(false);
        getContentPane().add(tfCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 295, 368, 37));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 365, -1, -1));

        jId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jId.setText("ID Member");
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 134, 117, -1));

        jGenre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGenre.setText("Tipe Paket");
        getContentPane().add(jGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 241, -1, -1));

        jJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jJudul.setText("Nama");
        getContentPane().add(jJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 194, 55, 16));

        jHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jHarga.setText("Coach");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 300, 67, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dialog/2222.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-33, -5, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, 
        "Data yang dihapus tidak dapat dikembalikan. Lanjutkan?", 
        "Konfirmasi Delete", 
        JOptionPane.YES_NO_OPTION);

if(confirm == JOptionPane.YES_OPTION){
    Connection conn = null;
    PreparedStatement ps = null;
    try {
        int idMember = Integer.parseInt(tfIdMember.getText());

        conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/DB_GYM",
                "postgres", "masryoo21");

        String sql = "DELETE FROM member_gym WHERE id_member=?";
        ps = conn.prepareStatement(sql);
        ps.setInt(1, idMember);

        int rowsDeleted = ps.executeUpdate();
        if(rowsDeleted > 0){
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            deleted = true; // <- ini penting
            dispose();       // tutup dialog setelah delete
        } else {
            JOptionPane.showMessageDialog(this, "Delete gagal, cek ID member!");
        }

    } catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } finally {
        try{
            if(ps != null) ps.close();
            if(conn != null) conn.close();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
}

    
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jGenre;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfCoach;
    private javax.swing.JTextField tfIdMember;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTipePaket;
    // End of variables declaration//GEN-END:variables
}
