/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;

/**
 *
 * 
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//blom
public class InsertDialog extends javax.swing.JDialog {

    // simpan model dari parent
    private boolean saved = false;

    // Constructor sesuai pemanggilan di FilmBioskop: (this, true, model)
   public InsertDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
   
    public boolean isSaved() {
        return saved;
    }

   

 

// Ambil data film dari textfield
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGenre = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        jJudul = new javax.swing.JLabel();
        jId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfIdMember = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfTipePaket = new javax.swing.JTextField();
        tfCoach = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jGenre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGenre.setText("Tipe Paket");
        getContentPane().add(jGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 106, -1));

        jHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jHarga.setText("Coach");
        getContentPane().add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jJudul.setText("Nama");
        getContentPane().add(jJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 55, 16));

        jId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jId.setText("ID Member");
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MASUKKAN DATA MEMBER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));
        getContentPane().add(tfIdMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 142, 344, 40));

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        getContentPane().add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 344, 40));

        tfTipePaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipePaketActionPerformed(evt);
            }
        });
        getContentPane().add(tfTipePaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 344, 40));
        getContentPane().add(tfCoach, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 344, 40));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dialog/2222.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
 try {
        // Validasi ID
        if(tfIdMember.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Member harus diisi!");
            return;
        }

        int idMember = Integer.parseInt(tfIdMember.getText().trim());
        String nama = tfNama.getText().trim();
        String tipe = tfTipePaket.getText().trim();
        String coach = tfCoach.getText().trim();

        if(nama.isEmpty() || tipe.isEmpty() || coach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }

        Connection conn = DriverManager.getConnection(
                "jdbc:postgresql://localhost:5432/DB_GYM",
                "postgres",
                "masryoo21"
        );

        String sql = "INSERT INTO member_gym(id_member, nama, tipe_paket, coach) VALUES(?,?,?,?)";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, idMember);
        pstmt.setString(2, nama);
        pstmt.setString(3, tipe);
        pstmt.setString(4, coach);

        int rows = pstmt.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            saved = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan!");
        }

        conn.close();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID Member harus berupa angka!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSaveActionPerformed
//atas
    private void tfTipePaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipePaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipePaketActionPerformed

   

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jGenre;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfCoach;
    private javax.swing.JTextField tfIdMember;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTipePaket;
    // End of variables declaration//GEN-END:variables
}
